# Generated by Django 5.0.4 on 2024-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
    ]
