# Generated by Django 5.0.4 on 2024-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_alter_inscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='defaites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='egalites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='partie_jouees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='victoires',
            field=models.IntegerField(default=0),
        ),
    ]
