# Generated by Django 5.0.4 on 2024-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0003_alter_score_defaites_alter_score_egalites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='lien',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
    ]
