# Generated by Django 5.0.4 on 2024-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_alter_sponsor_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='nationalite',
            field=models.CharField(blank='True', max_length=80, null='True'),
        ),
    ]
